version: '3.5'

services:
  maintenance:
    image: wickerlabs/maintenance
    container_name: maintenance-page
    environment:
      TEAM_NAME: "Team name"
      TITLE: "Oops!"
      MAIL_ADDRESS: "mail@domain.com"
      LINK_COLOR: "#dc8100"
      PORT: 8080
    ports:
    - 80:8080